#!/bin/bash
#See skript väljastab 5 tärnide rida 3 tärniga, mille ees on jrk numbrid
#
for (( i = 1; i <= 5; i++ ))      ###Outer for loop###
do
echo -n "$i. "
    for (( j = 1 ; j <= 3; j++ )); do
        echo -n "* "
    done
   echo "" ### print the new line ###
done

