#!/bin/bash

# Skript lubab kasutajal sisestada mitu reisijat on grupis ning kohtade arvu bussis

echo -n "Sisesta reisjate arv grupis "
read reisijad
echo -n "Sisesta kohtade arv bussis "
read kohad

#See rida näitab, mitu bussi on täidetud 
echo "Täidetud bussid"
var1=$(("$reisijad / $kohad | bc"))
echo $var1

#See rida näitab, mitu inimest on maha jäänud
echo "Mahajäänud inimesed"
var2=$(($reisijad % $kohad))
echo $var2

#See rida näitab, mitu bussi oleks vaja, et kõik ära mahuksid
if test $var2 -gt 0;
   then bussid=$(($var1 + 1))
fi
#tulemused
echo "Kokku on vaja $bussid bussi"




