#!/bin/bash

# see skript lubab kasutajale sisestada kuu numbri
# ja väljastab, millise aastaajaga on tegemist

echo -e "Sisesta kuu number \c"
read kuu
#
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then
        echo "see on talvekuu"
elif test $kuu -ge 3 -a $kuu -le 5
then
        echo "see on kevadkuu"
elif test $kuu -ge 6 -a $kuu -le 8
then
        echo "see on suvekuu"
elif test $kuu -ge 9 -a $kuu -le 11
then
        echo "see on talvekuu"
else
        echo "antud kuu numbrit pole"
fi

