#!/bin/bash
#
# see skript lubab kasutajale sisestada kellaaja (tundide arv)
# tervitab kasutajat vastavalt sisestatud väärtustele

echo -e "Sisesta aja väärtus: \c"
read aeg
user=$(whoami)
#kontrollime
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
       echo "Tere hommikust, $user!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
       echo "Tere päevast, $user !"
elif [ $aeg -ge 18 -a $aeg -lt 22]; then
       echo "Tere õhtust, $user!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
       echo "Head ööd, $user!"
else
       echo "Vale sisend, $user"
fi
#skritpi lõpp


