#!/bin/bash

#See skript küsib kasutaja käest ühe täisarvu
#ja väljastab kirjelduse, kas arv on paaris või paaritu arv

echo -n "Sisesta suvaline täisarv "
read arv

if [[ $((arv % 2)) -eq 0 ]];
   then echo "Antud arv on paaris" 
   else echo "Antud arv on paaritu" 
fi

